### ISSUE TITLE
Remove/simplify xclip alias

### ISSUE THREAD

**Issue by Slackadays** [exbotanical/dotfiles#1]
I just found your dotfiles after searching GH for all mentions of `xclip`, and in commit https://github.com/exbotanical/dotfiles/commit/b0f0b6ac7b627c4ed2914e3237dbe38a2020c32d I saw you added an extra alias file just for xclip. However, my project Clipboard would let you simplify this so that there's no alias at all because all there is for it is `cb`. I wanted to make this suggestion to help compact your dotfiles :)

**Comment by exbotanical** [comment]
Gotta commend you for a clever way to spread the word about your project. I'm always game to try new tools. I'll try it out and let you know what I think!

**Comment by exbotanical** [comment]
@Slackadays I really dig clipboard. Glad you suggested it ;)

https://github.com/exbotanical/dotfiles/commit/dd27d39031607d022e7089470c7c891471736c57

**Comment by Slackadays** [comment]
Thanks! 🙌
